UI remake
stefanodefaria/team-generator pull request #1
Opened 2024-10-01 22:48 UTC by leogianfagna

Cria primeira versão visual do site, de forma **responsiva**, limpa e simples. Também implementa funcionalidades de copiar texto automaticamente.

![image](https://github.com/user-attachments/assets/f926c068-accf-4195-98a3-fe80417ebed8)
![image](https://github.com/user-attachments/assets/86f4e14c-7adf-421d-b5ab-6ea40ef6ee26)

Não foi testado em versão mobile, mas por ter programado de forma responsiva, deve funcionar sem problemas. Qualquer _desalinhamento_ corrijo conforme necessidade.

2024-10-02 00:04 UTC, stefanodefaria requested changes
1. tira essa cor verde pelamordedeus, usa qualquer outra que vc quiser
2. fonte preta após selecionar times (não é melhor branco?)
3. UI quebrada em mobile

github pages foi atualizado pra esse branch pra facilitar testes

2024-10-02 02:20 UTC, leogianfagna commented
![image](https://github.com/user-attachments/assets/9cce90a4-890a-4053-b2af-85e5b3561dc9)
Em branco fica assim, legal até, mas força mais pra ver. vou deixar

2024-10-02 02:26 UTC, leogianfagna commented
@stefanodefaria deu tempo de corrigir hoje, usei o vídeo seu lá e ta tudo certo nos aparelhos, testei no meu cel também e deu bom. 

Agora a cor verde fica pra depois, tenho que trocar todas as paletas e eu particularmente gostei dessa kkkkkk. proxima semana eu testo uma nova.

_Sugestão to-do later: condição mobile se clicar em gerar time, sobe a tela para o topo._

2024-10-03 13:32 UTC, stefanodefaria approved these changes

2024-10-03 13:33 UTC, merged